return {
 ["name:TeX Gyre Cursor/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bold.otf", false },
 ["name:TeX Gyre Cursor/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bold.otf", false },
 ["name:TeX Gyre Cursor/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bolditalic.otf", false },
 ["name:TeX Gyre Cursor/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bolditalic.otf", false },
 ["name:TeX Gyre Cursor/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-italic.otf", false },
 ["name:TeX Gyre Cursor/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-italic.otf", false },
 ["name:TeX Gyre Cursor:mode=node;#717617"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeX Gyre Cursor:mode=node;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeX Gyre Cursor:mode=node;script=latn;language=dflt;#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeX Gyre Cursor:mode=node;script=latn;language=dflt;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeX Gyre Heros/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["name:TeX Gyre Heros/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["name:TeX Gyre Heros/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bolditalic.otf", false },
 ["name:TeX Gyre Heros/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bolditalic.otf", false },
 ["name:TeX Gyre Heros/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-italic.otf", false },
 ["name:TeX Gyre Heros/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-italic.otf", false },
 ["name:TeX Gyre Heros:mode=node;#717617"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeX Gyre Heros:mode=node;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeX Gyre Heros:mode=node;script=latn;language=dflt;#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeX Gyre Heros:mode=node;script=latn;language=dflt;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeX Gyre Pagella Math/B:mode=base;script=math;language=dflt;#b#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;#717617"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;#717619"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=0;#531038"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=1;#394691"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;#717619"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=0;#531038"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=1;#394691"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;#717619"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=0;#531038"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella Math:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=1;#394691"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeX Gyre Pagella/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bold.otf", false },
 ["name:TeX Gyre Pagella/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bold.otf", false },
 ["name:TeX Gyre Pagella/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bolditalic.otf", false },
 ["name:TeX Gyre Pagella/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bolditalic.otf", false },
 ["name:TeX Gyre Pagella/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-italic.otf", false },
 ["name:TeX Gyre Pagella/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-italic.otf", false },
 ["name:TeX Gyre Pagella:mode=node;#717617"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeX Gyre Pagella:mode=node;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeX Gyre Pagella:mode=node;script=latn;language=dflt;#717620"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeX Gyre Pagella:mode=node;script=latn;language=dflt;#717621"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeX Gyre Pagella:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeXGyreCursor/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bold.otf", false },
 ["name:TeXGyreCursor/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bold.otf", false },
 ["name:TeXGyreCursor/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bolditalic.otf", false },
 ["name:TeXGyreCursor/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-bolditalic.otf", false },
 ["name:TeXGyreCursor/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-italic.otf", false },
 ["name:TeXGyreCursor/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-italic.otf", false },
 ["name:TeXGyreCursor:mode=node;#717617"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeXGyreCursor:mode=node;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeXGyreCursor:mode=node;script=latn;language=dflt;#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeXGyreCursor:mode=node;script=latn;language=dflt;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrecursor-regular.otf", false },
 ["name:TeXGyreHeros/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["name:TeXGyreHeros/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["name:TeXGyreHeros/B:mode=node;script=latn;language=dflt;+tlig;#b#1359217"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["name:TeXGyreHeros/B:mode=node;script=latn;language=dflt;+tlig;#b#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bold.otf", false },
 ["name:TeXGyreHeros/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bolditalic.otf", false },
 ["name:TeXGyreHeros/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-bolditalic.otf", false },
 ["name:TeXGyreHeros/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-italic.otf", false },
 ["name:TeXGyreHeros/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-italic.otf", false },
 ["name:TeXGyreHeros:mode=node;#717617"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeXGyreHeros:mode=node;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeXGyreHeros:mode=node;script=latn;language=dflt;#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeXGyreHeros:mode=node;script=latn;language=dflt;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeXGyreHeros:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyreheros-regular.otf", false },
 ["name:TeXGyrePagella/B:mode=node;script=latn;language=dflt;#b#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bold.otf", false },
 ["name:TeXGyrePagella/B:mode=node;script=latn;language=dflt;#b#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bold.otf", false },
 ["name:TeXGyrePagella/BI:mode=node;script=latn;language=dflt;#bi#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bolditalic.otf", false },
 ["name:TeXGyrePagella/BI:mode=node;script=latn;language=dflt;#bi#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-bolditalic.otf", false },
 ["name:TeXGyrePagella/I:mode=node;script=latn;language=dflt;#i#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-italic.otf", false },
 ["name:TeXGyrePagella/I:mode=node;script=latn;language=dflt;#i#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-italic.otf", false },
 ["name:TeXGyrePagella:mode=node;#717617"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeXGyrePagella:mode=node;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeXGyrePagella:mode=node;script=latn;language=dflt;#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeXGyrePagella:mode=node;script=latn;language=dflt;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeXGyrePagella:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/texgyrepagella-regular.otf", false },
 ["name:TeXGyrePagellaMath/B:mode=base;script=math;language=dflt;#b#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.08;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:kernfactor=0.1;mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;#717617"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;#717620"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;#717621"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex2;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;#717619"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=0;#531038"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
 ["name:TeXGyrePagellaMath:mode=base;script=math;language=dflt;mathfontdimen=xetex;mathfontdimen=tex3;+ssty=1;#394691"]={ "/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/texgyrepagella-math.otf", false },
}